version: 2.1

orbs:
  heroku: circleci/heroku@1.2
  browser-tools: circleci/browser-tools@1.2.3

jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:8.0
      - image: circleci/openjdk:11-jdk
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=davcamalv_filmApp-back
      - run:
          name: Build
          command: mvn -B clean package -P pro

workflows:
  sample:
    jobs:
      - build-and-test:
          context: SonarCloud
          filters:
            branches:
              only: 
              - develop
      - heroku/deploy-via-git:
          force: true
          requires:
            - build-and-test
          filters:
            branches:
              only: 
              - develop