version: 2.1

orbs:
  heroku: circleci/heroku@1.2
  browser-tools: circleci/browser-tools@1.2.3

jobs:
  sonar:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=davcamalv_filmApp-back
  check_sonar_quality_gate:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Checking Sonar quality gate (develop and master)
          command: |
            SONAR_PROJECT_STATUS=$(curl -s -X GET "https://sonarcloud.io/api/qualitygates/project_status?projectKey=davcamalv_filmApp-back&branch=develop" | jq ".projectStatus.status")
            if [[ $SONAR_PROJECT_STATUS != "\"OK\"" ]]
            then
              echo -e "ERROR: SONAR QUALITY GATE NOT PASSED. STATUS "$SONAR_PROJECT_STATUS
              false
            else echo -e "SONAR QUALITY GATE PASSED. STATUS "$SONAR_PROJECT_STATUS
            fi
  build:  
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package -P pro

workflows:
  sample:
    jobs:
      - sonar:
          context: SonarCloud
          filters:
            branches:
              only: 
              - develop
              - master
      - check_sonar_quality_gate:
          context: SonarCloud
          requires:
              - sonar
          filters:
            branches:
              only: 
              - develop
              - master
      - build:
          requires:
            - check_sonar_quality_gate
          filters:
            branches:
              only: 
              - develop
              - master
      - heroku/deploy-via-git:
          force: true
          requires:
            - build
          filters:
            branches:
              only: 
              - develop
              - master
