version: 2.1

orbs:
  heroku: circleci/heroku@1.2

jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

workflows:
  sample:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          force: true
          requires:
            - build-and-test
          filters:
            branches:
              only: 
		- develop